name: Autograder
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  grading:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]' 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
           path: submission

      - name: Run Autograder
        uses: webtech-network/autograder@main
        with: 
          template-preset : "webdev"
          feedback-type: "default"
          include-feedback: "true"
          openai-key: ${{ secrets.ENGINE }}